### ISSUE TITLE
Weird sorting under the registered vouchers

### ISSUE THREAD

**Issue by Mickkkkkkk** [cybernetisk/internsystem-v2#27]
Seems to be interpret dates as numbers/floats? 30.08, 29.08, 27.08... is at the top, while 01.09, 02.09, 03.09... is on the bottom.

**Comment by ubesluttsom** [comment]
I think that it's sorted by date, but _ascending_, and not _descending_. You can tap the “usage date” column header to fix this. But it should perhaps have a different default? Either different sorting, or that the last page is shown instead of the first one?

Oh, and this is an issue with the “Use voucher” tab, not the “Register work” one.

**Comment by Mickkkkkkk** [comment]
<img width="46" alt="1" src="https://github.com/user-attachments/assets/45b45072-ae0d-4c85-8962-fd1ae4111261">
<img width="56" alt="2a" src="https://github.com/user-attachments/assets/bfe45132-2870-4630-82f7-dd3b4137b3a4">
<img width="44" alt="2" src="https://github.com/user-attachments/assets/d7590224-9356-4d40-9cdc-3e2a81088352">

This is how it is sorted under the "Register Work" tab. Talked to Eric about it and he knows how to fix it (something about the default sorting is actually not by date, but some hidden column). Changing the sorting to be ascending just reverses it, still being weird. Switching to another sort then back however fixes the issue.

**Comment by EricSvebakk** [comment]
The issue was that the wrong default column was selected for table initialization. First column would initially be sorted as strings, not numbers. Issue is fixed.
